class AppimageTmuxAT34Next < Formula
  desc "Formula to install AppImage tmux-eaw-HEAD-9ef854f5-x86_64.AppImage, generated by `brew appimage-install` command."
  homepage "https://github.com/z80oolong/tmux-eaw-appimage/releases/"

  url "https://github.com/z80oolong/tmux-eaw-appimage/releases/download/v3.4-CURRENT_HEAD/tmux-eaw-HEAD-9ef854f5-x86_64.AppImage"
  sha256 "fbd0bc9011c49ee226c7ddfbd94504c30a8cdbc4bac56c2a0ef091b2dc3cf79d"
  version "HEAD-9ef854f5"
  revision 50

  keg_only :versioned_formula

  option "with-extract", "Extract appimagetool AppImage."

  def install
    (buildpath/"tmux-eaw-HEAD-9ef854f5-x86_64.AppImage").chmod(0755)
    bin.mkdir; libexec.mkdir

    if build.with?("extract") then
      libexec.cd do
        system "#{buildpath}/tmux-eaw-HEAD-9ef854f5-x86_64.AppImage", "--appimage-extract"
      end
      bin.install_symlink (libexec/"squashfs-root/AppRun") => "tmux"
    else
      (libexec/"bin").mkpath
      (libexec/"bin").install "#{buildpath}/tmux-eaw-HEAD-9ef854f5-x86_64.AppImage"
      bin.install_symlink (libexec/"bin/tmux-eaw-HEAD-9ef854f5-x86_64.AppImage") => "tmux"
    end
  end
end
