class AppimageTmuxAT33 < Formula
  desc "Formula to install AppImage tmux-eaw-3.3-x86_64.AppImage, generated by `brew appimage-install` command."
  homepage "https://github.com/z80oolong/tmux-eaw-appimage/releases/"

  url "https://github.com/z80oolong/tmux-eaw-appimage/releases/download/v3.3_50/tmux-eaw-3.3-x86_64.AppImage"
  sha256 "f62980c888de9eef7adbd41c03000e240c984bdfcbc53f3e97f2f6a8ff8c465a"
  version "3.3"
  revision 50

  keg_only :versioned_formula

  option "with-extract", "Extract appimagetool AppImage."

  def install
    (buildpath/"tmux-eaw-3.3-x86_64.AppImage").chmod(0755)
    bin.mkdir; libexec.mkdir

    if build.with?("extract") then
      libexec.cd do
        system "#{buildpath}/tmux-eaw-3.3-x86_64.AppImage", "--appimage-extract"
      end
      bin.install_symlink (libexec/"squashfs-root/AppRun") => "tmux"
    else
      (libexec/"bin").mkpath
      (libexec/"bin").install "#{buildpath}/tmux-eaw-3.3-x86_64.AppImage"
      bin.install_symlink (libexec/"bin/tmux-eaw-3.3-x86_64.AppImage") => "tmux"
    end
  end
end
