class AppimageTmuxAT29 < Formula
  desc "Formula to install AppImage tmux-eaw-2.9-x86_64.AppImage, generated by `brew appimage-install` command."
  homepage "file:///vagrant/opt/releases/tmux-eaw-2.9-x86_64.AppImage"

  url "https://github.com/z80oolong/tmux-eaw-appimage/releases/download/v3.3a-eaw-appimage-0.1.5/tmux-eaw-2.9-x86_64.AppImage"
  sha256 "ddccd7d9bc87c9a3dfa8b3024e4155346f6518d4e1e025184f45fc8d43a0131a"
  version "2.9"
  revision 42

  keg_only :versioned_formula

  option "with-extract", "Extract appimagetool AppImage."

  def install
    (buildpath/"tmux-eaw-2.9-x86_64.AppImage").chmod(0755)
    bin.mkdir; libexec.mkdir

    if build.with?("extract") then
      libexec.cd do
        system "#{buildpath}/tmux-eaw-2.9-x86_64.AppImage", "--appimage-extract"
      end
      bin.install_symlink (libexec/"squashfs-root/AppRun") => "tmux"
    else
      (libexec/"bin").mkpath
      (libexec/"bin").install "#{buildpath}/tmux-eaw-2.9-x86_64.AppImage"
      bin.install_symlink (libexec/"bin/tmux-eaw-2.9-x86_64.AppImage") => "tmux"
    end
  end
end
