class AppimageTmuxAT32 < Formula
  desc "Formula to install AppImage tmux-eaw-3.2-x86_64.AppImage, generated by `brew appimage-install` command."
  homepage "https://github.com/z80oolong/tmux-eaw-appimage/releases/"

  url "https://github.com/z80oolong/tmux-eaw-appimage/releases/download/v3.2_50/tmux-eaw-3.2-x86_64.AppImage"
  sha256 "ea6abeaa0562aeb6caf6e40bf990be2fd3a47ae39e85086ced1e9a4fdc3b5fb5"
  version "3.2"
  revision 50

  keg_only :versioned_formula

  option "with-extract", "Extract appimagetool AppImage."

  def install
    (buildpath/"tmux-eaw-3.2-x86_64.AppImage").chmod(0755)
    bin.mkdir; libexec.mkdir

    if build.with?("extract") then
      libexec.cd do
        system "#{buildpath}/tmux-eaw-3.2-x86_64.AppImage", "--appimage-extract"
      end
      bin.install_symlink (libexec/"squashfs-root/AppRun") => "tmux"
    else
      (libexec/"bin").mkpath
      (libexec/"bin").install "#{buildpath}/tmux-eaw-3.2-x86_64.AppImage"
      bin.install_symlink (libexec/"bin/tmux-eaw-3.2-x86_64.AppImage") => "tmux"
    end
  end
end
