class AppimageTmuxAT28 < Formula
  desc "Formula to install AppImage tmux-eaw-2.8-x86_64.AppImage, generated by `brew appimage-install` command."
  homepage "https://github.com/z80oolong/tmux-eaw-appimage/releases/"

  url "https://github.com/z80oolong/tmux-eaw-appimage/releases/download/v2.8_50/tmux-eaw-2.8-x86_64.AppImage"
  sha256 "afa7b5600f21b27ede07b1a105c6326148e9bcc71e5f213f0e79ab3d9bb11a3e"
  version "2.8"
  revision 50

  keg_only :versioned_formula

  option "with-extract", "Extract appimagetool AppImage."

  def install
    (buildpath/"tmux-eaw-2.8-x86_64.AppImage").chmod(0755)
    bin.mkdir; libexec.mkdir

    if build.with?("extract") then
      libexec.cd do
        system "#{buildpath}/tmux-eaw-2.8-x86_64.AppImage", "--appimage-extract"
      end
      bin.install_symlink (libexec/"squashfs-root/AppRun") => "tmux"
    else
      (libexec/"bin").mkpath
      (libexec/"bin").install "#{buildpath}/tmux-eaw-2.8-x86_64.AppImage"
      bin.install_symlink (libexec/"bin/tmux-eaw-2.8-x86_64.AppImage") => "tmux"
    end
  end
end
