class AppimageTmuxAT33a < Formula
  desc "Formula to install AppImage tmux-eaw-3.3a-x86_64.AppImage, generated by `brew appimage-install` command."
  homepage "file:///vagrant/opt/releases/tmux-eaw-3.3a-x86_64.AppImage"

  url "https://github.com/z80oolong/tmux-eaw-appimage/releases/download/v3.3a-eaw-appimage-0.1.5/tmux-eaw-3.3a-x86_64.AppImage"
  sha256 "9231be75ae189388e545e474a6c7e069bb01e3c7295be9b2ae23dc814ef16ae5"
  version "3.3a"
  revision 42

  keg_only :versioned_formula

  option "with-extract", "Extract appimagetool AppImage."

  def install
    (buildpath/"tmux-eaw-3.3a-x86_64.AppImage").chmod(0755)
    bin.mkdir; libexec.mkdir

    if build.with?("extract") then
      libexec.cd do
        system "#{buildpath}/tmux-eaw-3.3a-x86_64.AppImage", "--appimage-extract"
      end
      bin.install_symlink (libexec/"squashfs-root/AppRun") => "tmux"
    else
      (libexec/"bin").mkpath
      (libexec/"bin").install "#{buildpath}/tmux-eaw-3.3a-x86_64.AppImage"
      bin.install_symlink (libexec/"bin/tmux-eaw-3.3a-x86_64.AppImage") => "tmux"
    end
  end
end
