class AppimageTmuxAT30a < Formula
  desc "Formula to install AppImage tmux-eaw-3.0a-x86_64.AppImage, generated by `brew appimage-install` command."
  homepage "https://github.com/z80oolong/tmux-eaw-appimage/releases/"

  url "https://github.com/z80oolong/tmux-eaw-appimage/releases/download/v3.0a_50/tmux-eaw-3.0a-x86_64.AppImage"
  sha256 "0285f3cff17037b5fa59727e12c9ff9982477226011059298e036ad95d459e14"
  version "3.0a"
  revision 50

  keg_only :versioned_formula

  option "with-extract", "Extract appimagetool AppImage."

  def install
    (buildpath/"tmux-eaw-3.0a-x86_64.AppImage").chmod(0755)
    bin.mkdir; libexec.mkdir

    if build.with?("extract") then
      libexec.cd do
        system "#{buildpath}/tmux-eaw-3.0a-x86_64.AppImage", "--appimage-extract"
      end
      bin.install_symlink (libexec/"squashfs-root/AppRun") => "tmux"
    else
      (libexec/"bin").mkpath
      (libexec/"bin").install "#{buildpath}/tmux-eaw-3.0a-x86_64.AppImage"
      bin.install_symlink (libexec/"bin/tmux-eaw-3.0a-x86_64.AppImage") => "tmux"
    end
  end
end
