class AppimageTmuxAT33a < Formula
  desc "Formula to install AppImage tmux-eaw-3.3a-x86_64.AppImage, generated by `brew appimage-install` command."
  homepage "https://github.com/z80oolong/tmux-eaw-appimage/releases/"

  url "https://github.com/z80oolong/tmux-eaw-appimage/releases/download/v3.3a_50/tmux-eaw-3.3a-x86_64.AppImage"
  sha256 "e57921bf70c0d0d542c82e170d6eb2a09d7a18e71cfdd176f2ff4dcea6278eda"
  version "3.3a"
  revision 50

  keg_only :versioned_formula

  option "with-extract", "Extract appimagetool AppImage."

  def install
    (buildpath/"tmux-eaw-3.3a-x86_64.AppImage").chmod(0755)
    bin.mkdir; libexec.mkdir

    if build.with?("extract") then
      libexec.cd do
        system "#{buildpath}/tmux-eaw-3.3a-x86_64.AppImage", "--appimage-extract"
      end
      bin.install_symlink (libexec/"squashfs-root/AppRun") => "tmux"
    else
      (libexec/"bin").mkpath
      (libexec/"bin").install "#{buildpath}/tmux-eaw-3.3a-x86_64.AppImage"
      bin.install_symlink (libexec/"bin/tmux-eaw-3.3a-x86_64.AppImage") => "tmux"
    end
  end
end
