class AppimageTmuxAT28 < Formula
  desc "Formula to install AppImage tmux-eaw-2.8-x86_64.AppImage, generated by `brew appimage-install` command."
  homepage "file:///vagrant/opt/releases/tmux-eaw-2.8-x86_64.AppImage"

  url "https://github.com/z80oolong/tmux-eaw-appimage/releases/download/v3.3a-eaw-appimage-0.1.5/tmux-eaw-2.8-x86_64.AppImage"
  sha256 "a4b941e03ca68f714d6b738e90253ff2a0d25da3951c8f75ced5bbe38e5432e4"
  version "2.8"
  revision 42

  keg_only :versioned_formula

  option "with-extract", "Extract appimagetool AppImage."

  def install
    (buildpath/"tmux-eaw-2.8-x86_64.AppImage").chmod(0755)
    bin.mkdir; libexec.mkdir

    if build.with?("extract") then
      libexec.cd do
        system "#{buildpath}/tmux-eaw-2.8-x86_64.AppImage", "--appimage-extract"
      end
      bin.install_symlink (libexec/"squashfs-root/AppRun") => "tmux"
    else
      (libexec/"bin").mkpath
      (libexec/"bin").install "#{buildpath}/tmux-eaw-2.8-x86_64.AppImage"
      bin.install_symlink (libexec/"bin/tmux-eaw-2.8-x86_64.AppImage") => "tmux"
    end
  end
end
