class AppimageTmuxAT31c < Formula
  desc "Formula to install AppImage tmux-eaw-3.1c-x86_64.AppImage, generated by `brew appimage-install` command."
  homepage "https://github.com/z80oolong/tmux-eaw-appimage/releases/"

  url "https://github.com/z80oolong/tmux-eaw-appimage/releases/download/v3.1c_50/tmux-eaw-3.1c-x86_64.AppImage"
  sha256 "9f97849f7a30695d509da62481e9cc8298e1092e0d1590ed52caa6a5140a9555"
  version "3.1c"
  revision 50

  keg_only :versioned_formula

  option "with-extract", "Extract appimagetool AppImage."

  def install
    (buildpath/"tmux-eaw-3.1c-x86_64.AppImage").chmod(0755)
    bin.mkdir; libexec.mkdir

    if build.with?("extract") then
      libexec.cd do
        system "#{buildpath}/tmux-eaw-3.1c-x86_64.AppImage", "--appimage-extract"
      end
      bin.install_symlink (libexec/"squashfs-root/AppRun") => "tmux"
    else
      (libexec/"bin").mkpath
      (libexec/"bin").install "#{buildpath}/tmux-eaw-3.1c-x86_64.AppImage"
      bin.install_symlink (libexec/"bin/tmux-eaw-3.1c-x86_64.AppImage") => "tmux"
    end
  end
end
