class AppimageTmuxAT34Next < Formula
  desc "Formula to install AppImage tmux-eaw-HEAD-0a0ded32-x86_64.AppImage, generated by `brew appimage-install` command."
  homepage "file:///vagrant/opt/releases/tmux-eaw-HEAD-0a0ded32-x86_64.AppImage"

  url "https://github.com/z80oolong/tmux-eaw-appimage/releases/download/v3.3a-eaw-appimage-0.1.5/tmux-eaw-HEAD-0a0ded32-x86_64.AppImage"
  sha256 "cc7366eadd87c3c162968a795b1b16ca4db1d2d2e28832777617d92b082f98ce"
  version "HEAD-0a0ded32"
  revision 42

  keg_only :versioned_formula

  option "with-extract", "Extract appimagetool AppImage."

  def install
    (buildpath/"tmux-eaw-HEAD-0a0ded32-x86_64.AppImage").chmod(0755)
    bin.mkdir; libexec.mkdir

    if build.with?("extract") then
      libexec.cd do
        system "#{buildpath}/tmux-eaw-HEAD-0a0ded32-x86_64.AppImage", "--appimage-extract"
      end
      bin.install_symlink (libexec/"squashfs-root/AppRun") => "tmux"
    else
      (libexec/"bin").mkpath
      (libexec/"bin").install "#{buildpath}/tmux-eaw-HEAD-0a0ded32-x86_64.AppImage"
      bin.install_symlink (libexec/"bin/tmux-eaw-HEAD-0a0ded32-x86_64.AppImage") => "tmux"
    end
  end
end
